### ISSUE TITLE
Newest Linux version for Tinkerboard

### ISSUE THREAD

**Issue by mfaccin** [TinkerBoard/debian#1]
Hi! I have an old Tinkerboard (non-S, the standard model) and would like to play around with some of the peripherals -- very cool board. My problem right now is the latest python version is 3.5. 

Supposing it is due to the usage of the Debian stretch, where can I find the official binaries of the newer releases?

**Comment by asus-leslieyu** [comment]
Hi you can find the latest Debian Buster release for Tinker Board (S) here.
https://dlcdnets.asus.com/pub/ASUS/Embedded_IPC/TinkerBoard_R2.0/Tinker_Board-Debian-Buster-v3.0.11-20211026.zip

It looks like the latest releases are not listed for Tinker Board.
https://tinker-board.asus.com/download-list.html?product=tinker-board

**Comment by mfaccin** [comment]
hi @asus-leslieyu , thank you for the quick response! 

how did you arrive at this link/destination?
after a lot of research, I found a Bullseye version at https://www.armbian.com/tinkerboard/, but I'm honestly a little confused and not sure how to compare the versions and select the right one to follow. do you have any tips?

**Comment by asus-leslieyu** [comment]
Hi,
The armbian one is different. For the Tinker OS, you can go to the Tinker Board website as the following.
https://tinker-board.asus.com/index.html

Then you can select Download -> Tinker OS -> DOWNLOAD to go to the list as the following.
https://tinker-board.asus.com/download-list.html

And select product Tinker Board S to list the images. Please select for Tinker Board S first. I don't know why the images are not listed for Tinker Board. They should be the same. I will figure it out.

Thanks a lot!
Leslie

**Comment by mfaccin** [comment]
Got you, thanks!
